import Head from "next/head";

import { Main } from "../components/Main";
import { PostContainer, PostTitle } from "../components/PostCard";
import GlobalStyle from "../styles/globalStyles";
import Header from "../components/Header";
import Button from "../components/Button";

type Post = {
  userId: number;
  id: number;
  title: string;
  body: string;
};

type PostProps = {
  posts: Post[];
};

export async function getStaticProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const posts = await res.json();

  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }: PostProps) {
  return (
    <>
      <GlobalStyle />
      <Head>
        <title>Posts Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main>
        <div className="container">
          {/* <h1 style={{ textAlign: "center" }}>Postagens</h1> */}
          <PostContainer>
            {posts.map((post) => {
              return <PostTitle key={post.id}>{post.title}</PostTitle>;
            })}
          </PostContainer>
        </div>
        <Button />
      </Main>
    </>
  );
}
