import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Link from "next/link";
import Top from "../components/Header";
import { PostContainer, PostTitle } from "../components/PostCard";

type Post = {
  id: number;
  title: string;
  body: string;
  author: string;
};

type PostProps = {
  posts: Post[];
};

export default function Home({ posts }: PostProps) {
  const [counter, setCounter] = useState(0);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Top />
        <div>
          <Link href="/add">Adicionar Postagem</Link>
          <h1>Next js introduction</h1>
          <h2>{counter}</h2>
          <button onClick={() => setCounter((c) => c + 1)}>+</button>
          <PostContainer>
            {posts.map((post) => (
              <PostTitle key={post.id}>{post.title}</PostTitle>
            ))}
          </PostContainer>
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://127.0.0.1:7000/api/posts");
  const posts = await res.json();

  return {
    props: {
      posts,
    },
  };
}
